### ISSUE TITLE
multiple videos

### ISSUE THREAD

**Issue by kenaku** [stefanerickson/covervid#14]
Hi! Thanks fo great plugin!
Can you tell me how to initialize multiple videos on page? 
If I add same  class="covervid-video" - only first one is working...

**Comment by stefanerickson** [comment]
If you are using jQuery I'd suggest wrapping it as an each function,like this...

$(''.covervid-video").each(function(){
  $(this).coverVid(1920, 1080);
});

Although this would mean every video needs to be 1920 x 1080.

The alternative would be to have a different class name for each one and call each individually.

I will be looking into a way to call multiple videos at once more conveniently.
