### ISSUE TITLE
video doesn't resize on safari

### ISSUE THREAD

**Issue by HarrisRobin** [stefanerickson/covervid#15]
Hi,

I have noticed that the video does not properly resize on the latest safari browsers. Try the demo on safari to see.

Cheers,

**Comment by stefanerickson** [comment]
Unable to duplicate this issue.

**Comment by fieldoffice** [comment]
The demo doesn't use a poster image which is why it works in Safari. Adding this causes the video to not scale.

**Comment by erichquist** [comment]
Yeah, I can't seem to get it to work in the latest Safari, either. It works in one case, but not another.

**Comment by erichquist** [comment]
And by "work" I mean in cover 100% of the browser width or height, depending on size of browser.

**Comment by erichquist** [comment]
Err, I thought I tried everything. I'm not sure what changed, but it's working now.
