### ISSUE TITLE
Play button shows on iOS device

### ISSUE THREAD

**Issue by travisjtodd** [stefanerickson/covervid#18]
I know this plugin is not compatible with iOS Safari and have a fallback image in my code but the play button still shows up on the device. Is there a way to ensure that the video is hidden on iOS?

Here's a screengrab:

![screen shot 2015-01-18 at 16 13 21](https://cloud.githubusercontent.com/assets/47908/5792872/f519ab34-9f2c-11e4-9c11-8012fc395af3.png)

**Comment by JonathanWolfe** [comment]
The play button comes from the browser detecting the <video> element. Just `display: none` it or destroy the element on mobile.

**Comment by travisjtodd** [comment]
Thanks. That's a workaround for sure. But shouldn't proper mobile detection be done by JS and therefore this should ideally live within the plugin?

**Comment by JonathanWolfe** [comment]
I can see an argument for both sides taking care of it. 

I think that it's the user's job to take care of that, but this is a jQuery plugin which are more likely to be used by people who wouldn't take that extra step.

I'll see if I can write that today and I'll submit a PR later.

**Comment by chrislentz** [comment]
Did you ever add support for disabling it on mobile? I think it would be nice to have a pluign setting. Something like  "hide-on-mobile: true/false"

**Comment by JonathanWolfe** [comment]
Nope, I completely forgot about this.

**Comment by chaddanna** [comment]
Can't seem to find a way to get the selector for the play button. It doesn't show on a resized browser window on the computer, and I don't have an inspector on my phone. Anyone have the solution for this?
Thanks

**Comment by stefanerickson** [comment]
Just built in support to handle poster images as a cover image on the parent element and hide the video when it is not supported. Pull the latest and the should work ;)
