### ISSUE TITLE
Compress or change video in CoverVid website

### ISSUE THREAD

**Issue by migswd** [stefanerickson/covervid#22]
Hi thank you for this great plugin.
But I think you should change (or compress more) the video used in example page
http://stefanerickson.github.io/covervid/

Because on my side the video play and stop regularly, buffering problems I presume.
It does not help to trust your plugin I think as the video does not play well...

**Comment by stefanerickson** [comment]
Agree, it was a way to large of file for the purpose of background video. Appreciate the suggestion and just pushed a cut down compressed version of the video.

Thanks
