### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by al3d** [stefanerickson/covervid#25]
It's published to bower, and package.json exists, so why not publish to npm, too? More options for us to install it.

Thanks!

**Comment by SamEureka** [comment]
+1

**Comment by seppentoni** [comment]
+1

**Comment by RobLoach** [comment]
https://github.com/stefanerickson/covervid/pull/38
https://www.npmjs.com/package/covervid

**Comment by stefanerickson** [comment]
This project is no longer maintained now that their is widespread support for the [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) and [`object-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-position) CSS properties in modern browsers
