### ISSUE TITLE
Fallback image does not show on ipad

### ISSUE THREAD

**Issue by Libowitz** [stefanerickson/covervid#26]
hi, very nice plugin, thanks a lot.
One question: If i look at the Demo http://stefanerickson.github.io/covervid/ on ipad, i can't see a fallback-image, cause the demo doesn't have a poster definition. When I try to ad one 
like  - see the second comment - 
still nothing shows up. Thanks a lot for any help.

**Comment by Libowitz** [comment]
sorry, here's the code I tried
<pre><code>
<video class="masthead-video" autoplay loop poster="img/video-fallback.png">
<source src="assets/videos/dreamscapes.mp4" type="video/mp4">
<source src="assets/videos/dreamscapes.webm" type="video/webm">
</video>
</code></pre>

**Comment by Libowitz** [comment]
<video class="masthead-video" autoplay loop poster="img/video-fallback.png">
        	<source src="assets/videos/dreamscapes.mp4" type="video/mp4">
			<source src="assets/videos/dreamscapes.webm" type="video/webm">
		</video>

**Comment by Libowitz** [comment]
<video class="masthead-video" autoplay loop poster="img/video-fallback.png">
        	<source src="assets/videos/dreamscapes.mp4" type="video/mp4">
			<source src="assets/videos/dreamscapes.webm" type="video/webm">
		</video>

**Comment by stefanerickson** [comment]
Just added all new support for fallback images. Please test it out now ;)

We are now taking the defined poster image of the video element and applying it as a style on the parent element to make it behave like a proper "cover" image (native poster is not handled this way exactly). We are also checking for HTML5 video support and for device and removing the video if not supported properly to make sure the fallback image is visible.
