### ISSUE TITLE
CoverVid doesn't fit container if container is bigger than the video

### ISSUE THREAD

**Issue by Stephen0208** [stefanerickson/covervid#30]
In my installation if the screen is bigger than the video then the video does not fit its container, see attached screenshot. But as soon as the viewport/window is resized the video snaps to fit.

Any ideas why this would be happening?

Thanks.

![covervid](https://cloud.githubusercontent.com/assets/4642868/8331044/c2270768-1a7d-11e5-838c-be81b97b97bf.jpg)

**Comment by wmarsh** [comment]
I experienced the same issue. My workaround is along these lines:

    var vw = 1280;
    var vh = 720;
    $video.coverVid(vw, vh);
    
    var initialScale = Math.max(
	    $videoContainer.outerWidth() / vw,
	    $videoContainer.outerHeight() / vh
    );
    
    $video.css({
	    width: vw * initialScale + "px",
	    height: vh * initialScale + "px"
    });

**Comment by Stephen0208** [comment]
Thanks, I will give that a go and see how I get on.

**Comment by Stephen0208** [comment]
wmarsh, this worked a like a charm. Thank you!

**Comment by wmarsh** [comment]
Glad it helped. I think the issue should still be open, as we're having to replicate the functionality of the library to get it to work properly on initialize :-)

**Comment by Rasora** [comment]
This script works fine, its just that it needs to run before the document loads.

Wrong :
```
$(document).ready(function() {
  return $('.covervid-video').coverVid(1280, 720);
});
```

Right : 
```
$('.covervid-video').coverVid(1280, 720);
```

**Comment by stefanerickson** [comment]
Just pushed a fix for this, see latest commit ;)
