### ISSUE TITLE
Consider adding tags for the repo.

### ISSUE THREAD

**Issue by Piicksarn** [stefanerickson/covervid#31]
Hi~
Adding tags for repo could specify points in history and mark release points.
It's helpful for user to know the version and status of repository, and would enable wider distribution of the library, for example on [CDNJS](https://github.com/cdnjs/cdnjs)
Would you please consider on using tags?

Thanks for your great work!!
Piicksarn

**Comment by milesmatthias** [comment]
I'm also not able to install this via bower without tags apparently:

```
bower covervid#~1.0.0     ENORESTARGET No tag found that was able to satisfy ~1.0.0
```

**Comment by stereodenis** [comment]
http://take.ms/YE75L

**Comment by stefanerickson** [comment]
This project is no longer maintained now that their is widespread support for the [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) and [`object-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-position) CSS properties in modern browsers
