### ISSUE TITLE
Consider removing the video files from the repo

### ISSUE THREAD

**Issue by Jursdotme** [stefanerickson/covervid#34]
I was installing this via bower but stopped it after downloading 45megs. The video files are not necesary in the repo and should be hosted elswhere. I dont want unused video files filling up by project folders.

**Comment by mmikkel** [comment]
+1

**Comment by stefanerickson** [comment]
Good call. Will look into hosting elsewhere.

**Comment by Apercu** [comment]
:+1:

**Comment by stefanerickson** [comment]
This project is no longer maintained now that their is widespread support for the [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) and [`object-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-position) CSS properties in modern browsers
