### ISSUE TITLE
Fade in poster/video? 

### ISSUE THREAD

**Issue by Taapo** [stefanerickson/covervid#36]
Right now, I see the poster appearing quickly, then switching to the video - is this normal behaviour? Is there a way we could fade both in during loading ... so that it's not that abrupt?

**Comment by stefanerickson** [comment]
This project is no longer maintained now that their is widespread support for the [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) and [`object-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-position) CSS properties in modern browsers
