### ISSUE TITLE
Kind hint for bootstrap jumbotron

### ISSUE THREAD

**Issue by Corsari** [stefanerickson/covervid#39]
Hello
I'm a fan of CoverVid, but unfortunately I'm not so strong with css

can you kindly hint on how to use your creation to use it as the jumbotron background in a bootstrap page?

Is that possible?

Thank you
R.

**Comment by Corsari** [comment]
Also, another kind hint. I'm trying to get i working by myself. I've replaced your demo videos with the one I want to use. 
Strange thing happen :-)
The two videos used in your demo, don't output the audio... while used in my test page, they output the audio.
Why this different behavior?
I've tried to understand if you have any javascript that removes the audio in the zip downloaded fro this github repository, but if any, i can't find it.
Thank you for any hint
Robert

**Comment by stefanerickson** [comment]
This project is no longer maintained now that their is widespread support for the [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) and [`object-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-position) CSS properties in modern browsers
