### ISSUE TITLE
There is no git tags on GitHub repository

### ISSUE THREAD

**Issue by mercyg** [stefanerickson/covervid#41]
Hi @stefanerickson, 

We are cdnjs team, we're going to host this library.
The git auto-updater in cdnjs relies on git tags so that it can recognize the correct version and automatically update the repo.
Could you please add git tags for the repo?

If you have any suggestions, please let me know.
Thank you.

cdnjs/cdnjs#11219

**Comment by stefanerickson** [comment]
[Check it out](https://github.com/stefanerickson/covervid/releases/tag/v1.0)

Thanks 🙌🏻
