### ISSUE TITLE
Background Image loading as null

### ISSUE THREAD

**Issue by mkess-ivy** [stefanerickson/covervid#43]
Hi - using the covervid.js plugin.  My poster image is set, however if the video doesnt load right away, I am seeing no background image or poster image.

I checked into the js, and the background image is loading as null for some reason.

Also, video is not loading at all on safari - is there a workaround for this?

![covervid-issue2](https://user-images.githubusercontent.com/8550694/32557409-11b375ca-c470-11e7-88d8-608a58abba1d.jpg)
![covervid-issue3](https://user-images.githubusercontent.com/8550694/32557410-11be3640-c470-11e7-8fac-8476b786c1c9.jpg)
![covervidjs-issue](https://user-images.githubusercontent.com/8550694/32557411-11c83820-c470-11e7-97f8-60893cfebc8f.jpg)

**Comment by dominikkucharski** [comment]
It happened to me when CoverVid was launched twice for the same element.

**Comment by stefanerickson** [comment]
This project is no longer maintained now that their is widespread support for the [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) and [`object-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-position) CSS properties in modern browsers
