### ISSUE TITLE
Minified version is not setting width and height

### ISSUE THREAD

**Issue by joergmoldenhauer** [stefanerickson/covervid#44]
When I use "covervid.min.js" the width and height of the video are not set. When I use "covervid.js" everything works just fine. There seems to be a problem with the minified version.

**Comment by joergmoldenhauer** [comment]
There already seems to be a pull-request fixing this problem: https://github.com/stefanerickson/covervid/pull/32

**Comment by stefanerickson** [comment]
This project is no longer maintained now that their is widespread support for the [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) and [`object-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-position) CSS properties in modern browsers
