### ISSUE TITLE
JS errors appear console when there is no .covervid-video element

### ISSUE THREAD

**Issue by laurend** [stefanerickson/covervid#45]
If the script is loaded on a page that doesn't actually contain an element with the class .covervid-video, errors appear in the console. Seems like something similar was addressed in #28 and was subsequently fixed. 

![screen shot 2018-02-13 at 10 04 34 am](https://user-images.githubusercontent.com/1125979/36156643-b17a94fe-10a5-11e8-93a9-f7b072bdd7d5.png)

**Comment by stefanerickson** [comment]
This project is no longer maintained now that their is widespread support for the [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) and [`object-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-position) CSS properties in modern browsers
