### ISSUE TITLE
Videos not loading in full width when shorter than screen width

### ISSUE THREAD

**Issue by idosius** [stefanerickson/covervid#46]
When the video is shorter than the screen width, e.g. the video is 800 pixels wide and the screen 1920 pixels wide, the video doesn't take up full screen width. 

Workaround: triggering the window resize event seems to fix it.

**Comment by stefanerickson** [comment]
This project is no longer maintained now that their is widespread support for the [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) and [`object-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-position) CSS properties in modern browsers
