### ISSUE TITLE
Cannot install using Yarn

### ISSUE THREAD

**Issue by zietbukuel** [stefanerickson/covervid#47]
I get the following error:

```
error covervid@1.0.0: The engine "node" is incompatible with this module. Expected version ">=4 <=5". Got "10.23.0"
error Found incompatible module.
```

**Comment by stefanerickson** [comment]
This project is no longer maintained now that their is widespread support for the [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) and [`object-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-position) CSS properties in modern browsers
