### ISSUE TITLE
Using it responsive with two video files

### ISSUE THREAD

**Issue by Shepstar** [stefanerickson/covervid#48]
Hey Stefan,

I have a problem as I would like to use a Video as Background for our page: www.ruff-cycles.com/xpro2/video.html
But I would like to also use one video for the desktop version and one for the mobile version. So the video does still make sense.
Once I switch to the mobile version it seems the Covervid is not loading the video correct. I guess it cannot handle two videos for this purpose and uses the wrong size for full screen background.
Any idea how I can get this done? Thanks
Stefan

**Comment by stefanerickson** [comment]
This project is no longer maintained now that their is widespread support for the [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) and [`object-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-position) CSS properties in modern browsers
